// Copyright © 2026 Victor Rodrigues (@victorrodriguessf). Consulte LICENSE.
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Link, NavLink, Navigate, Route, Routes, useLocation, useParams, useSearchParams } from 'react-router-dom';
import { animate, createScope, stagger } from 'animejs';
import { ArrowRight, ArrowUpRight, Building2, CalendarDays, Check, ChevronRight, CircleHelp, ClipboardList, Edit3, FlaskConical, LogOut, Plus, RefreshCw, Search, ShieldCheck, Stethoscope, Users, X } from 'lucide-react';
import { apiFetch, useAuth } from './auth';
import { labelCase, normalized, type GuideData, type GuideUnit, type GuideProfessional, type GuideExam, type Placement } from './guide-types';
import { ProfessionalForm, UnitForm, ExamForm, type SaveRecord } from './GuideForms';
interface Props { data: GuideData; editPerson: (person?: GuideProfessional, unitId?: string) => void; editUnit: (unit: GuideUnit) => void; editExam: (unitId: string, exam?: GuideExam) => void }
const unique=(values:string[])=>[...new Set(values)].sort((a,b)=>a.localeCompare(b,'pt-BR'));
const unitLink=(id:string)=>`/unidades/${encodeURIComponent(id)}`;
const personLink=(unitId:string,id:string)=>`${unitLink(unitId)}/profissionais/${encodeURIComponent(id)}`;
const specLink=(unitId:string,spec:string)=>`${unitLink(unitId)}/especialidades/${encodeURIComponent(spec)}`;
const activePlacement=(p:GuideProfessional,unitId:string)=>p.placements.find(a=>a.unitId===unitId&&a.active);
const cnpjLabel=(cnpj:string)=>cnpj?cnpj.replace(/^(.{2})(.{3})(.{3})(.{4})(.{2})$/,'$1.$2.$3/$4-$5'):'CNPJ não informado';
function Badge({children}:{children:ReactNode}){return <span className="badge">{children}</span>;}
function BrandImage({unit}:{unit:GuideUnit}){return unit.logo?<img src={unit.logo} alt={unit.name}/>:<span className="text-brand"><Building2 size={24}/>{unit.short}</span>;}
function Breadcrumb({children}:{children?:ReactNode}){return <nav className="breadcrumbs" aria-label="Caminho de navegação"><Link to="/">Unidades</Link>{children}</nav>;}
function Crumb({children,to}:{children:ReactNode;to?:string}){return <><ChevronRight size={13}/>{to?<Link to={to}>{children}</Link>:<span aria-current="page">{children}</span>}</>;}
function Empty({title,children,action}:{title:string;children:ReactNode;action?:ReactNode}){return <div className="empty"><div className="empty-icon"><Search size={25}/></div><h3>{title}</h3><p>{children}</p>{action}</div>;}
function Query({value,onChange,placeholder='Buscar nesta unidade…',label='Buscar nesta unidade'}:{value:string;onChange:(v:string)=>void;placeholder?:string;label?:string}){return <label className="search-control"><Search size={17}/><input aria-label={label} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/>{value&&<button className="icon-button" aria-label="Limpar busca" onClick={()=>onChange('')}><X size={15}/></button>}</label>;}
function Select({label,value,onChange,values}:{label:string;value:string;onChange:(v:string)=>void;values:string[]}){return <select aria-label={label} value={value} onChange={e=>onChange(e.target.value)} className="filter-select"><option value="">{label}</option>{values.map(v=><option key={v}>{v}</option>)}</select>;}
export default function App(){
 const [data,setData]=useState<GuideData|null>(null);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const [editor,setEditor]=useState<{type:'professional';person?:GuideProfessional;unitId?:string}|{type:'unit';unit:GuideUnit}|{type:'exam';unitId:string;exam?:GuideExam}|null>(null);
 const {logout}=useAuth();const [leaving,setLeaving]=useState(false);const location=useLocation();const root=useRef<HTMLDivElement>(null);
 const load=async(signal?:AbortSignal)=>{const response=await apiFetch('/api/guide',{signal});if(!response.ok)throw new Error('Não foi possível carregar o guia da rede. Tente novamente.');setData(await response.json());setError('');};
 useEffect(()=>{const controller=new AbortController();load(controller.signal).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[]);
 useEffect(()=>{if(!data||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const scope=createScope({root}).add(()=>{animate('.reveal',{opacity:[0,1],translateY:[12,0],duration:500,delay:stagger(45),ease:'out(3)'});});return()=>scope.revert();},[!!data,location.pathname]);
 useEffect(()=>{window.scrollTo(0,0);setMessage('');},[location.pathname]);
 const save:SaveRecord=async(kind,id,record,revision)=>{const response=await apiFetch(`/api/guide/${kind}${id?`/${encodeURIComponent(id)}`:''}`,{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({record,revision})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Não foi possível salvar.');setData(result.guide);setMessage('Cadastro salvo com sucesso.');};
 const props:Props={data:data!,editPerson:(person,unitId)=>setEditor({type:'professional',person,unitId}),editUnit:unit=>setEditor({type:'unit',unit}),editExam:(unitId,exam)=>setEditor({type:'exam',unitId,exam})};
 const exit=async()=>{setLeaving(true);try{await logout();}catch{setError('Não foi possível sair. Tente novamente.');setLeaving(false);}};
 if(!data)return <div className="loading">{error?<><h1>Vamos tentar novamente?</h1><p role="alert">{error}</p><button className="button primary" onClick={()=>load().catch(e=>setError(e.message))}>Recarregar dados</button></>:<><span className="loading-ring"/><p>Preparando o guia da nossa rede…</p></>}</div>;
 return <div className="guide-app" ref={root}><a className="skip-link" href="#content">Pular para o conteúdo</a><header className="guide-header"><Link to="/" className="guide-brand" aria-label="Oncology Group — início"><img src="/logos/oncology.png" alt="Oncology Group"/><span/><div>Guia da rede<small>PROFISSIONAIS E SERVIÇOS</small></div></Link><nav aria-label="Navegação principal"><NavLink to="/" end>Unidades</NavLink><NavLink to="/profissionais">Profissionais</NavLink></nav><div className="header-actions"><button className="button primary" onClick={()=>props.editPerson()}><Plus size={16}/><span>Cadastrar profissional</span></button><button className="logout-button" onClick={exit} disabled={leaving} aria-label="Sair do sistema"><LogOut size={17}/><span>{leaving?'Saindo…':'Sair'}</span></button></div></header>
 <main id="content" className="guide-main">{message&&<div className="success-notice" role="status"><Check size={17}/>{message}<button className="icon-button" aria-label="Fechar aviso" onClick={()=>setMessage('')}><X size={15}/></button></div>}{error&&<div className="form-error" role="alert">{error}</div>}<Routes><Route path="/" element={<Home {...props}/>}/><Route path="/unidades/:unitId" element={<UnitPage {...props}/>}/><Route path="/unidades/:unitId/especialidades/:specialty" element={<SpecialtyPage {...props}/>}/><Route path="/unidades/:unitId/profissionais/:personId" element={<ProfessionalPage {...props}/>}/><Route path="/unidades/:unitId/exames/:examId" element={<ExamPage {...props}/>}/><Route path="/profissionais" element={<PeoplePage {...props}/>}/><Route path="/profissionais/:personId" element={<ProfessionalPage {...props}/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes><footer className="guide-footer"><span>Oncology Group <i/> Pessoas. Conexões. Cuidado.</span><span className="guide-footer-credit">Desenvolvido originalmente por <a href="https://github.com/victorrodriguessf" target="_blank" rel="noreferrer">Victor Rodrigues · @victorrodriguessf</a></span><button className="text-button" onClick={()=>load().then(()=>setMessage('Dados atualizados.')).catch(e=>setError(e.message))}><RefreshCw size={13}/>Atualizar dados</button></footer></main>
 {editor?.type==='professional'&&<ProfessionalForm data={data} person={editor.person} unitId={editor.unitId} save={save} close={()=>setEditor(null)}/>} {editor?.type==='unit'&&<UnitForm data={data} unit={editor.unit} save={save} close={()=>setEditor(null)}/>} {editor?.type==='exam'&&<ExamForm data={data} unitId={editor.unitId} exam={editor.exam} save={save} close={()=>setEditor(null)}/>}</div>;
}
function Home({data}:Props){
 const allSpecialties=unique(data.professionals.flatMap(p=>p.placements.filter(a=>a.active).flatMap(a=>a.specialties)));
 return <><section className="home-intro reveal"><div><div className="eyebrow">ONCOLOGY GROUP / GUIA DA REDE</div><h1>Pessoas que cuidam.<br/><span>Informações que conectam.</span></h1><p>Encontre os profissionais, as especialidades e os serviços<br className="desktop-break"/> de cada clínica. Comece escolhendo uma unidade.</p></div><div className="intro-mark" aria-hidden="true"><i/><i/><i/><i/><span>UM ECOSSISTEMA DE CUIDADO</span></div></section><div className="overview-numbers reveal"><div><Users size={19}/><strong>{data.professionals.length}</strong><span>profissionais na base</span></div><div><Building2 size={19}/><strong>{data.units.length}</strong><span>unidades da rede</span></div><div><Stethoscope size={19}/><strong>{allSpecialties.length}</strong><span>especialidades com vínculo ativo</span></div></div><section className="reveal"><div className="section-heading"><div><span className="eyebrow">NOSSA REDE</span><h2>Um cuidado próximo, em cada unidade.</h2><p>Informações de atendimento organizadas por clínica.</p></div><Badge>{data.units.length} unidades</Badge></div><div className="unit-grid">{data.units.map((u,i)=>{const people=data.professionals.filter(p=>activePlacement(p,u.id));const spec=unique(people.flatMap(p=>activePlacement(p,u.id)!.specialties));return <Link to={unitLink(u.id)} className="unit-tile" key={u.id} style={{'--unit-color':u.color} as React.CSSProperties}><div className="unit-tile-top"><span className="unit-index">0{i+1}</span><span className="round-arrow"><ArrowUpRight size={20}/></span></div><div className="unit-image"><BrandImage unit={u}/></div><h3>{u.name}</h3><p className="cnpj">{cnpjLabel(u.cnpj)}</p><div className="unit-tile-stats"><span><Users size={14}/>{people.length} profissionais</span><span>{spec.length} especialidades</span></div><div className="unit-tile-link">Explorar unidade<ArrowRight size={15}/></div></Link>;})}</div></section><div className="home-note reveal"><ShieldCheck size={23}/><div><strong>Cada unidade com suas informações.</strong><p>Convênios, dias de atendimento e exames são consultados no contexto da clínica selecionada.</p></div><span>Mais clareza para cuidar.</span></div></>;
}
function UnitPage(props:Props){
 const {unitId}=useParams();const unit=props.data.units.find(u=>u.id===unitId);const [params,setParams]=useSearchParams();const tab=params.get('aba')==='exames'?'exames':'especialidades';const [query,setQuery]=useState('');const [payer,setPayer]=useState('');const [day,setDay]=useState('');
 useEffect(()=>{setQuery('');setPayer('');setDay('');},[unitId,tab]);
 if(!unit)return <Missing/>;
 const people=props.data.professionals.filter(p=>activePlacement(p,unit.id));
 const filtered=people.filter(p=>{const a=activePlacement(p,unit.id)!;return (!payer||a.payers.includes(payer))&&(!day||a.schedules.some(s=>normalized(s.days).includes(day)));});
 const specialties=unique(filtered.flatMap(p=>activePlacement(p,unit.id)!.specialties)).filter(s=>normalized(s).includes(normalized(query))||filtered.some(p=>activePlacement(p,unit.id)!.specialties.includes(s)&&normalized(p.name).includes(normalized(query))));
 const exams=props.data.exams.filter(e=>e.unitId===unit.id&&e.active&&normalized(e.name+' '+e.category+' '+e.code).includes(normalized(query)));
 return <><Breadcrumb><Crumb>{unit.short}</Crumb></Breadcrumb><section className="unit-banner reveal"><div className="unit-banner-logo"><BrandImage unit={unit}/></div><div className="unit-banner-copy"><span className="eyebrow">UNIDADE DA REDE</span><h1>{unit.name}</h1><p>{unit.legalName?`${unit.legalName} · `:''}{cnpjLabel(unit.cnpj)}</p><div className="unit-banner-meta"><span><Users size={15}/>{people.length} profissionais</span><span><Stethoscope size={15}/>{unique(people.flatMap(p=>activePlacement(p,unit.id)!.specialties)).length} especialidades</span></div></div><button className="text-button" onClick={()=>props.editUnit(unit)}><Edit3 size={15}/>Dados da unidade</button></section><div className="unit-nav"><div role="tablist" aria-label="Conteúdo da unidade"><button role="tab" aria-selected={tab==='especialidades'} className={tab==='especialidades'?'active':''} onClick={()=>setParams({})}><Stethoscope size={17}/>Especialidades</button><button role="tab" aria-selected={tab==='exames'} className={tab==='exames'?'active':''} onClick={()=>setParams({aba:'exames'})}><FlaskConical size={17}/>Exames</button></div><button className="button secondary" onClick={()=>tab==='exames'?props.editExam(unit.id):props.editPerson(undefined,unit.id)}><Plus size={15}/>{tab==='exames'?'Cadastrar exame':'Cadastrar profissional'}</button></div><div className="filters"><Query value={query} onChange={setQuery} placeholder={tab==='exames'?'Buscar exame, categoria ou código…':'Buscar especialidade ou profissional…'}/>{tab==='especialidades'&&<><Select label="Todos os convênios" value={payer} onChange={setPayer} values={unique(people.flatMap(p=>activePlacement(p,unit.id)!.payers))}/><select aria-label="Todos os dias" className="filter-select" value={day} onChange={e=>setDay(e.target.value)}><option value="">Todos os dias</option>{['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'].map(d=><option key={d} value={normalized(d)}>{d}</option>)}</select></>}{(query||payer||day)&&<button className="text-button" onClick={()=>{setQuery('');setPayer('');setDay('');}}>Limpar filtros</button>}</div>
 {tab==='especialidades'?<><div className="results-heading"><h2>Especialidades</h2><span>{specialties.length} encontradas nesta unidade</span></div><div className="specialty-grid">{specialties.map((s,i)=><Link className="specialty-card" key={s} to={specLink(unit.id,s)}><span className={`specialty-icon tone-${i%4}`}><Stethoscope size={21}/></span><div><h3>{s}</h3><p>{people.filter(p=>activePlacement(p,unit.id)!.specialties.includes(s)).length} profissionais na especialidade</p></div><ArrowUpRight size={17}/></Link>)}</div>{!specialties.length&&<Empty title="Nenhuma especialidade encontrada">Altere os filtros ou cadastre um profissional nesta unidade.</Empty>}</>:<><div className="results-heading"><h2>Exames da unidade</h2><span>{exams.length} cadastrados e ativos</span></div><div className="exam-grid">{exams.map(e=><Link to={`${unitLink(unit.id)}/exames/${e.id}`} className="exam-card" key={e.id}><span className="specialty-icon"><FlaskConical size={22}/></span><Badge>{e.category||'Exame'}</Badge><h3>{e.name}</h3><p>{e.code?`Código ${e.code}`:'Código não informado'}</p><span className="card-link">Ver informações<ArrowRight size={15}/></span></Link>)}</div>{!exams.length&&<Empty title={query?'Nenhum exame encontrado':'Os exames desta unidade ainda não foram cadastrados.'} action={!query?<button className="button primary" onClick={()=>props.editExam(unit.id)}><Plus size={15}/>Cadastrar primeiro exame</button>:undefined}>{query?'Experimente outro termo de busca.':'Vincule os serviços oferecidos pela clínica. O catálogo da planilha está disponível no formulário para auxiliar o cadastro.'}</Empty>}{props.data.exams.some(e=>e.unitId===unit.id&&!e.active)&&<details className="inactive-exams"><summary>Exames inativos</summary>{props.data.exams.filter(e=>e.unitId===unit.id&&!e.active).map(e=><div key={e.id}><span>{e.name}</span><button className="text-button" onClick={()=>props.editExam(unit.id,e)}>Editar / reativar</button></div>)}</details>}</>}
 </>;
}
function PersonCard({person,unitId}:{person:GuideProfessional;unitId?:string}){const placement=unitId?activePlacement(person,unitId):undefined;return <Link className="person-card" to={unitId?personLink(unitId,person.id):`/profissionais/${person.id}`}><div className="person-avatar">{person.name.split(' ').filter(Boolean).slice(0,2).map(s=>s[0]).join('')}</div><div className="person-card-main"><h3>{labelCase(person.name)}</h3><span>{person.council} {person.registration}{person.uf?` / ${person.uf}`:''}</span><p>{placement?placement.specialties.join(' · '):`${person.placements.filter(a=>a.active).length} vínculos ativos`}</p></div><ArrowUpRight size={18}/>{placement&&<div className="person-card-foot"><span><CalendarDays size={14}/>{placement.schedules.length?'Horários informados':'Horários não informados'}</span><span>{placement.payers.length?`${placement.payers.length} convênios`:'Convênios não informados'}</span></div>}</Link>;}
function SpecialtyPage(props:Props){
 const {unitId,specialty}=useParams();const unit=props.data.units.find(u=>u.id===unitId);const [query,setQuery]=useState('');const [payer,setPayer]=useState('');
 if(!unit||!specialty)return <Missing/>;
 const people=props.data.professionals.filter(p=>activePlacement(p,unit.id)?.specialties.includes(specialty));
 const filtered=people.filter(p=>normalized(p.name+' '+p.registration).includes(normalized(query))&&(!payer||activePlacement(p,unit.id)!.payers.includes(payer)));
 return <><Breadcrumb><Crumb to={unitLink(unit.id)}>{unit.short}</Crumb><Crumb>{specialty}</Crumb></Breadcrumb><div className="page-title reveal"><div><span className="eyebrow">ESPECIALIDADE / {unit.short}</span><h1>{specialty}</h1><p>Conheça os profissionais e consulte as informações de atendimento nesta unidade.</p></div><button className="button secondary" onClick={()=>props.editPerson(undefined,unit.id)}><Plus size={16}/>Cadastrar profissional</button></div><div className="filters"><Query value={query} onChange={setQuery} placeholder="Buscar nome ou registro…"/><Select label="Todos os convênios" value={payer} onChange={setPayer} values={unique(people.flatMap(p=>activePlacement(p,unit.id)!.payers))}/></div><div className="results-heading"><h2>Profissionais</h2><span>{filtered.length} encontrados</span></div><div className="people-grid">{filtered.map(p=><PersonCard key={p.id} person={p} unitId={unit.id}/>)}</div>{!filtered.length&&<Empty title="Nenhum profissional encontrado">Confira os filtros ou cadastre um vínculo nesta especialidade.</Empty>}</>;
}
function ProfessionalPage(props:Props){
 const {unitId,personId}=useParams();const person=props.data.professionals.find(p=>p.id===personId);const unit=props.data.units.find(u=>u.id===unitId);const placement=person&&unit?person.placements.find(a=>a.unitId===unit.id):undefined;
 if(!person||unitId&&(!unit||!placement))return <Missing/>;
 return <><Breadcrumb>{unit?<Crumb to={unitLink(unit.id)}>{unit.short}</Crumb>:<Crumb to="/profissionais">Profissionais</Crumb>}<Crumb>{labelCase(person.name)}</Crumb></Breadcrumb><section className="profile-heading reveal"><div className="person-avatar large">{person.name.split(' ').slice(0,2).map(v=>v[0]).join('')}</div><div><span className="eyebrow">{unit?`CORPO CLÍNICO / ${unit.short}`:'CADASTRO DO PROFISSIONAL'}</span><h1>{labelCase(person.name)}</h1><p>{person.council} {person.registration}{person.uf?` / ${person.uf}`:' · UF não informada'}{person.rqe?` · RQE ${person.rqe}`:''}</p><div className="tag-list">{placement?.specialties.map(s=><Link className="badge" key={s} to={specLink(unit!.id,s)}>{s}</Link>)}</div></div><button className="button secondary" onClick={()=>props.editPerson(person)}><Edit3 size={15}/>Editar profissional</button></section>{person.notes&&<div className="info-note"><CircleHelp size={17}/><p>{person.notes}</p></div>}
 {placement&&unit?<>{!placement.active&&<div className="info-note">Este vínculo está inativo. Reative-o no cadastro para exibi-lo na unidade.</div>}<div className="profile-panels"><section className="panel"><div className="panel-heading"><span className="specialty-icon"><ShieldCheck size={21}/></span><div><h2>Convênios atendidos</h2><p>Informações de {unit.short}</p></div></div>{placement.payers.length?<div className="payer-grid">{placement.payers.map(p=><span key={p}><Check size={14}/>{labelCase(p)}</span>)}</div>:<div className="small-empty">Convênios não informados para este profissional nesta unidade.</div>}<p className="panel-note">A ausência de um convênio nesta lista não confirma que ele não seja atendido.</p></section><section className="panel"><div className="panel-heading"><span className="specialty-icon gold"><CalendarDays size={21}/></span><div><h2>Dias de atendimento</h2><p>Dias, turnos e observações da unidade</p></div></div>{placement.schedules.length?<div className="schedule-list">{placement.schedules.map((s,i)=><div key={i}><strong>{s.days||'Dia não informado'}</strong><span>{s.shift||'Turno não informado'}</span>{s.notes&&<p>{s.notes}</p>}</div>)}</div>:<div className="small-empty">Dias e turnos não informados para esta unidade.</div>}<p className="panel-note">Consulte a unidade para confirmar a disponibilidade de atendimento.</p></section></div>{placement.notes&&<section className="panel notes-panel"><h2>Observações de atendimento</h2><p>{placement.notes}</p></section>}</>:<><div className="section-heading"><div><h2>Unidades e vínculos</h2><p>Selecione a clínica para consultar convênios e horários específicos.</p></div></div><div className="affiliation-grid">{person.placements.map(a=>{const u=props.data.units.find(u=>u.id===a.unitId)!;return <Link key={a.unitId} to={personLink(a.unitId,person.id)} className="affiliation-card"><Building2 size={22}/><div><h3>{u.short}</h3><p>{a.specialties.join(' · ')}</p><small>{a.active?'Vínculo ativo':'Vínculo inativo'}</small></div><ArrowRight size={18}/></Link>;})}</div>{!person.placements.length&&<Empty title="Nenhuma unidade vinculada">Edite o cadastro para associar este profissional à clínica em que atende.</Empty>}</>}
 {unit&&person.placements.some(a=>a.unitId!==unit.id)&&<section className="other-units"><h3>Outros vínculos na rede</h3>{person.placements.filter(a=>a.unitId!==unit.id).map(a=><Link key={a.unitId} to={personLink(a.unitId,person.id)}>{props.data.units.find(u=>u.id===a.unitId)?.short}{!a.active?' · inativo':''}<ArrowUpRight size={14}/></Link>)}</section>}
 {person.divergences.length>0&&<div className="source-alert"><CircleHelp size={18}/><div><strong>Divergências registradas na planilha</strong>{person.divergences.map((text,i)=><p key={i}>{text}</p>)}</div></div>}
 <div className="record-meta"><span>{person.origin==='imported'?'Importado da planilha':person.origin==='updated'?'Cadastro importado e atualizado manualmente':'Cadastro manual'}{person.updatedAt?` · Atualizado em ${new Date(person.updatedAt).toLocaleString('pt-BR')}`:''}</span>{person.versions.length>0&&<details className="source-versions"><summary>Versões clínicas nas abas da planilha ({unit?person.versions.filter(v=>v.unitId===unit.id).length:person.versions.length})</summary><div>{person.versions.filter(v=>!unit||v.unitId===unit.id).map((v,i)=><div className="source-version" key={i}><strong>{v.source.sheet} · {v.source.cell}</strong><span>{v.name} · {v.specialty}</span><small>RQE: {v.rqe||'não informado'} · Dias: {v.days||'não informados'} · Turno: {v.shift||'não informado'}</small></div>)}</div></details>}{person.sources.length>0&&!person.versions.length&&<details><summary>Referências do cadastro original</summary>{person.sources.map((s,i)=><p key={i}>{s.sheet} · {s.cell}</p>)}</details>}</div></>;
}
function PeoplePage(props:Props){const [query,setQuery]=useState('');const [page,setPage]=useState(0);const people=props.data.professionals.filter(p=>normalized(p.name+' '+p.council+' '+p.registration).includes(normalized(query)));const pages=Math.max(1,Math.ceil(people.length/18));const current=Math.min(page,pages-1);return <><Breadcrumb><Crumb>Profissionais</Crumb></Breadcrumb><div className="page-title reveal"><div><span className="eyebrow">ADMINISTRAÇÃO DO CORPO CLÍNICO</span><h1>Profissionais da rede</h1><p>Cadastre, atualize e organize os vínculos de cada profissional.</p></div><Badge>{props.data.professionals.length} cadastros</Badge></div><div className="filters"><Query label="Buscar profissional" value={query} onChange={v=>{setQuery(v);setPage(0);}} placeholder="Buscar nome, conselho ou registro…"/></div><div className="people-grid">{people.slice(current*18,current*18+18).map(p=><PersonCard key={p.id} person={p}/>)}</div>{!people.length&&<Empty title="Nenhum profissional encontrado">Tente outro nome ou número de registro.</Empty>}<div className="pagination"><span>{people.length} cadastros encontrados</span><div><button disabled={current===0} onClick={()=>setPage(current-1)}>Anterior</button><span>{current+1} / {pages}</span><button disabled={current===pages-1} onClick={()=>setPage(current+1)}>Próxima</button></div></div></>;}
function ExamPage(props:Props){const {unitId,examId}=useParams();const unit=props.data.units.find(u=>u.id===unitId);const exam=props.data.exams.find(e=>e.id===examId&&e.unitId===unitId);if(!unit||!exam)return <Missing/>;return <><Breadcrumb><Crumb to={unitLink(unit.id)}>{unit.short}</Crumb><Crumb to={`${unitLink(unit.id)}?aba=exames`}>Exames</Crumb><Crumb>{exam.name}</Crumb></Breadcrumb><div className="page-title reveal"><div><span className="eyebrow">EXAMES / {unit.short}</span><h1>{exam.name}</h1><p>{exam.code?`Código ${exam.code} · `:''}{exam.category||'Categoria não informada'}{!exam.active?' · Inativo':''}</p></div><button className="button secondary" onClick={()=>props.editExam(unit.id,exam)}><Edit3 size={15}/>Editar exame</button></div><div className="profile-panels"><section className="panel notes-panel"><h2>Informações do exame</h2><p>{exam.description||'Nenhuma informação adicional cadastrada.'}</p></section><section className="panel notes-panel"><h2>Convênios informados</h2>{exam.payers.length?<div className="payer-grid">{exam.payers.map(p=><span key={p}><Check size={14}/>{p}</span>)}</div>:<p>Convênios não informados para este exame nesta unidade.</p>}</section></div><div className="section-heading"><h2>Profissionais associados ao exame</h2></div><div className="people-grid">{props.data.professionals.filter(p=>exam.professionalIds.includes(p.id)&&activePlacement(p,unit.id)).map(p=><PersonCard key={p.id} person={p} unitId={unit.id}/>)}</div>{!exam.professionalIds.length&&<Empty title="Profissionais não informados">O exame ainda não possui profissionais associados neste cadastro.</Empty>}</>;}
function Missing(){return <Empty title="Cadastro não encontrado" action={<Link className="button primary" to="/">Voltar às unidades</Link>}>Este endereço não corresponde a um cadastro disponível.</Empty>;}
