import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { NavLink, useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { animate, createScope, stagger, spring } from 'animejs';
import { ArrowDownToLine, ArrowRight, ArrowUpRight, Building2, CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, ClipboardList, Database, FileCheck2, FileSpreadsheet, HeartPulse, LayoutDashboard, Menu, Search, ShieldCheck, SlidersHorizontal, Stethoscope, Users, X, AlertCircle, Layers3, Link2, FileText, RotateCcw, LogOut } from 'lucide-react';
import { apiFetch, useAuth } from './auth';
import type { Library, Source, Workbook } from './types';
const norm = (s: string) => s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
const title = (s: string) => s.toLocaleLowerCase('pt-BR').replace(/(^|\s|\/)(\p{L})/gu, (_m, a: string, b: string) => a + b.toUpperCase());
const money = (v: number | null, raw = '') => v === null ? (raw || 'Não informado') : v.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const date = (v: string | null) => v ? v.split('T')[0].split('-').reverse().join('/') : 'Não informado';
const unitName = (id: string) => ({ GROUP: 'Oncology Group', GENERAL: 'Cadastro geral', COMN: 'COMN', OC: 'Oncoclínicas', CSM: 'São Marcos', PROMATER: 'Promater', MOSSORO: 'Mossoró', '*': 'Compartilhado' }[id] || id || 'Não informada');
const nav = [ ['/', 'Visão geral', LayoutDashboard], ['/corpo-clinico', 'Corpo clínico', Stethoscope], ['/atendimentos', 'Dias de atendimento', CalendarDays], ['/convenios', 'Convênios e valores', ShieldCheck], ['/credenciamento', 'Credenciamentos', FileCheck2], ['/procedimentos', 'Procedimentos', ClipboardList], ['/equipe', 'Equipe e organização', Users] ] as const;
interface DisplayRow { id: string; cells: string[]; source?: Source; sources?: Source[]; details?: Record<string,string>; status?: string }
interface Detail { title: string; values: Record<string,string>; sources: Source[] }
function download(name: string, content: string, type: string) { const url = URL.createObjectURL(new Blob([content], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function csvValue(s: string) { const safe = /^[=+@\-\t\r]/.test(s) ? `'${s}` : s; return `"${safe.replaceAll('"', '""')}"`; }
function Badge({ children, tone = '' }: {children: ReactNode; tone?: string}) { return <span className={`badge ${tone}`}>{children}</span>; }
function Filter({ label, value, options, onChange }: {label: string; value: string; options: {value: string; label: string}[]; onChange: (v: string) => void}) { return <label className="select-control"><span className="sr-only">{label}</span><select aria-label={label} value={value} onChange={e => onChange(e.target.value)}><option value="">{label}</option>{options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select><ChevronDown size={14}/></label>; }
const options = (values: string[]) => [...new Set(values.filter(Boolean))].sort((a,b) => a.localeCompare(b,'pt-BR')).map(v => ({value:v,label:title(v)}));
function DataTable({ columns, rows, onDetail, label = 'registros', toolbar }: {columns: string[]; rows: DisplayRow[]; onDetail: (d: Detail) => void; label?: string; toolbar?: ReactNode}) {
 const [page,setPage] = useState(0); const [sort,setSort] = useState<{col:number;reverse:boolean}>({col:-1,reverse:false});
 const sorted = useMemo(() => sort.col < 0 ? rows : [...rows].sort((a,b) => a.cells[sort.col].localeCompare(b.cells[sort.col],'pt-BR',{numeric:true})*(sort.reverse?-1:1)),[rows,sort]);
 const pages = Math.max(1,Math.ceil(sorted.length/12)); const current=Math.min(page,pages-1);
 useEffect(() => setPage(0),[rows]);
 const exportCsv = () => download('oncology-consulta.csv','\ufeff'+[columns.concat('Origem'),...sorted.map(r=>r.cells.concat((r.sources || (r.source?[r.source]:[])).map(s=>`${s.sheet}!${s.cell}`).join(' | ')))].map(r=>r.map(csvValue).join(';')).join('\r\n'),'text/csv;charset=utf-8');
 return <section className="panel data-panel"><div className="table-toolbar"><span><strong>{rows.length.toLocaleString('pt-BR')}</strong> {label}</span><div>{toolbar}<button className="text-button" onClick={exportCsv} disabled={!rows.length}><ArrowDownToLine size={15}/> Exportar consulta</button></div></div><div className="table-scroll"><table><thead><tr>{columns.map((c,i)=><th key={c} aria-sort={sort.col===i?(sort.reverse?'descending':'ascending'):'none'}><button onClick={()=>setSort({col:i,reverse:sort.col===i?!sort.reverse:false})}>{c}<ChevronDown size={12}/></button></th>)}<th><span className="sr-only">Detalhes</span></th></tr></thead><tbody>{sorted.slice(current*12,current*12+12).map(r=><tr key={r.id}>{r.cells.map((c,i)=><td key={i}>{i===0?<span className="primary-cell">{c||'Não informado'}</span>:r.status===c?<Badge tone={c==='Credenciado'?'green':c==='Em andamento'?'amber':'neutral'}>{c}</Badge>:c||<span className="muted">Não informado</span>}</td>)}<td><button className="icon-button" aria-label={`Ver detalhes de ${r.cells[0]}`} onClick={()=>onDetail({title:r.cells[0]||'Registro da planilha',values:r.details||Object.fromEntries(columns.map((c,i)=>[c,r.cells[i]||'Não informado'])),sources:r.sources||(r.source?[r.source]:[])})}><ArrowUpRight size={16}/></button></td></tr>)}</tbody></table>{rows.length===0&&<div className="empty-state"><Search size={30}/><h3>Nenhum registro encontrado</h3><p>Experimente outro termo ou remova os filtros.</p></div>}</div><div className="pagination"><span>{rows.length?`${current*12+1}–${Math.min(current*12+12,rows.length)} de ${rows.length}`:'0 registros'}</span><div><button className="icon-button" aria-label="Página anterior" disabled={current===0} onClick={()=>setPage(current-1)}><ChevronLeft size={16}/></button><span>Página {current+1} de {pages}</span><button className="icon-button" aria-label="Próxima página" disabled={current===pages-1} onClick={()=>setPage(current+1)}><ChevronRight size={16}/></button></div></div></section>;
}
function DetailDialog({ detail, close, openSource }: {detail: Detail|null;close:()=>void;openSource:(s:Source)=>void}) {
 const ref=useRef<HTMLDialogElement>(null); const [reveal,setReveal]=useState(false);
 useEffect(()=>{setReveal(false); if(detail) ref.current?.showModal();else ref.current?.close();},[detail]);
 return <dialog ref={ref} onCancel={close} onClick={e=>{if(e.target===ref.current)close();}} className="detail-dialog">{detail&&<><div className="dialog-heading"><div><span className="eyebrow">CONSULTA DO REGISTRO</span><h2>{detail.title}</h2></div><button className="icon-button" aria-label="Fechar detalhes" onClick={close}><X/></button></div><dl>{Object.entries(detail.values).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{/CPF|nascimento/i.test(k)&&!reveal?'••• · dado pessoal':v||'Não informado'}</dd></div>)}</dl>{Object.keys(detail.values).some(k=>/CPF|nascimento/i.test(k))&&<button className="text-button" onClick={()=>setReveal(!reveal)}>{reveal?'Ocultar':'Mostrar'} dados pessoais</button>}<div className="source-list"><h3><FileSpreadsheet size={16}/> Origem na planilha</h3>{detail.sources.map((s,i)=><button key={i} onClick={()=>{close();openSource(s);}}><span>{s.sheet}</span><code>{s.cell}</code><ArrowUpRight size={14}/></button>)}</div></>}</dialog>;
}
export default function App() {
 const { logout } = useAuth(); const [logoutBusy,setLogoutBusy]=useState(false); const [logoutError,setLogoutError]=useState('');
 const handleLogout=async()=>{setLogoutBusy(true);setLogoutError('');try{await logout();}catch{setLogoutError('Não foi possível sair. Tente novamente.');}finally{setLogoutBusy(false);}};
 const [data,setData]=useState<Library|null>(null);const [error,setError]=useState('');const [detail,setDetail]=useState<Detail|null>(null);const [mobile,setMobile]=useState(false);const [unit,setUnit]=useState('');const [query,setQuery]=useState('');
 const location=useLocation();const navigate=useNavigate();const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{const controller=new AbortController();apiFetch('/api/library',{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error('Não foi possível carregar a biblioteca. Verifique a extração e o servidor.');return r.json();}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[]);
 useEffect(()=>{setMobile(false);setQuery('');},[location.pathname]);
 useEffect(()=>{if(!data||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const scope=createScope({root}).add(()=>{animate('.reveal',{opacity:[0,1],translateY:[14,0],delay:stagger(45),duration:620,ease:spring({bounce:.08,duration:620})});});return()=>scope.revert();},[data,location.pathname]);
 const openSource=(s:Source)=>{navigate(`/base?aba=${s.sheetId}&linha=${s.row}`);};
 if(error)return <div className="loading"><AlertCircle/><h1>Não foi possível abrir a base</h1><p>{error}</p><button className="button primary" onClick={()=>window.location.reload()}>Tentar novamente</button></div>;
 if(!data)return <div className="loading"><span className="loading-ring"/><p>Organizando as informações da sua rede…</p></div>;
 const activeTitle=nav.find(n=>n[0]===location.pathname)?.[1]||({'/base':'Biblioteca de dados','/qualidade':'Qualidade da base'}[location.pathname]||'Página não encontrada');
 const go=(path:string)=>navigate(path);
 return <div className="app" ref={root}><a className="skip-link" href="#content">Pular para o conteúdo</a>{mobile&&<button className="sidebar-backdrop" aria-label="Fechar menu" onClick={()=>setMobile(false)}/>}
 <aside className={`sidebar ${mobile?'is-open':''}`}><NavLink to="/" className="brand" aria-label="Oncology Group — início"><img src="/logos/oncology.png" alt="Oncology Group"/></NavLink><div className="workspace-label"><span className="workspace-icon"><Layers3 size={17}/></span><div>Organização Oncology<small>Gestão integrada da rede</small></div></div><p className="nav-caption">ESPAÇO DE TRABALHO</p><nav aria-label="Navegação principal">{nav.map(([url,label,Icon])=><NavLink end={url==='/'} to={url} key={url}><Icon size={18}/><span>{label}</span>{url==='/'&&<span className="nav-dot"/>}</NavLink>)}</nav><p className="nav-caption second">INFORMAÇÕES</p><nav aria-label="Informações da base"><NavLink to="/base"><Database size={18}/>Biblioteca de dados<small>19</small></NavLink><NavLink to="/qualidade"><AlertCircle size={18}/>Qualidade da base<small>{data.issues.length}</small></NavLink></nav><div className="sidebar-bottom"><div className="local-status"><span/> Ambiente local <Badge>Consulta</Badge></div><div className="sidebar-note"><ShieldCheck size={17}/><p>Uma visão compartilhada.<br/><strong>Mais clareza para cuidar.</strong></p></div></div></aside>
 <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Abrir menu" onClick={()=>setMobile(!mobile)}><Menu/></button><span>Workspace</span><ChevronRight size={13}/><strong>{activeTitle}</strong></div><div className="topbar-right"><span className="source-status"><span/> Base Excel importada</span><button className="icon-button help-button" aria-label="Sobre esta base" onClick={()=>setDetail({title:'Sobre esta base',values:{'Arquivo':data.meta.source,'Abas':String(data.meta.sheetCount),'Linhas com conteúdo':data.meta.nonemptyRows.toLocaleString('pt-BR'),'Extração':new Date(data.meta.extractedAt).toLocaleString('pt-BR'),'Modo':'Consulta local. Alterações na planilha exigem nova extração.','Versões':'As divergências são preservadas. Nenhuma aba foi eleita como fonte definitiva.'},sources:[]})}><CircleHelp size={19}/></button><span className="avatar" title="Administrador">AD</span><button className="logout-button" onClick={handleLogout} disabled={logoutBusy} aria-label="Sair do sistema"><LogOut size={17}/><span>{logoutBusy?'Saindo…':'Sair'}</span></button>{logoutError&&<span role="alert" className="logout-error">{logoutError}</span>}</div></header>
 <main id="content"><div className="page-heading reveal"><div><div className="eyebrow">ONCOLOGY GROUP <span>/</span> GESTÃO E INTELIGÊNCIA</div><h1>{location.pathname==='/'?'Sua rede, em uma só visão.':activeTitle}</h1><p>{location.pathname==='/'?'Pessoas, convênios e oportunidades. Tudo conectado para facilitar o seu dia.':descriptions[location.pathname]||'O endereço informado não existe.'}</p></div><button className="button secondary" onClick={()=>download('oncology-biblioteca.json',JSON.stringify(data,null,2),'application/json')}><ArrowDownToLine size={16}/><span>Exportar biblioteca</span></button></div>
 {location.pathname!=='/base'&&location.pathname!=='/qualidade'&&<div className="global-filters reveal"><label className="search-control"><Search size={18}/><input aria-label="Buscar nesta visão" placeholder={location.pathname==='/'?'Buscar profissionais, convênios ou procedimentos…':'Buscar nesta visão…'} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="icon-button" aria-label="Limpar busca" onClick={()=>setQuery('')}><X size={14}/></button>}</label><Filter label="Todas as unidades" value={unit} onChange={setUnit} options={data.units.map(u=>({value:u.id,label:u.short}))}/>{(query||unit)&&<button className="text-button" onClick={()=>{setQuery('');setUnit('');}}><RotateCcw size={14}/> Limpar</button>}</div>}
 {location.pathname==='/'?(query?<SearchResults data={data} query={query} unit={unit} onDetail={setDetail}/>:<Dashboard data={data} unit={unit} setUnit={setUnit} go={go} onDetail={setDetail}/>):location.pathname==='/base'?<WorkbookView data={data}/>:location.pathname==='/qualidade'?<Quality data={data} onDetail={setDetail}/>:nav.some(n=>n[0]===location.pathname)?<Records key={location.pathname} path={location.pathname} data={data} unit={unit} query={query} onDetail={setDetail}/>:<div className="empty-state"><h2>Página não encontrada</h2><button className="button primary" onClick={()=>go('/')}>Voltar ao início</button></div>}
 <footer className="page-footer"><span><span className="footer-dot"/> Informações extraídas de {data.meta.source}</span><span>{data.meta.sheetCount} abas · Consulta com rastreabilidade</span></footer></main></div><DetailDialog detail={detail} close={()=>setDetail(null)} openSource={openSource}/></div>;
}
const descriptions:Record<string,string>={'/corpo-clinico':'Conheça os profissionais, especialidades e vínculos de cada unidade.','/atendimentos':'Consulte os dias e turnos informados na planilha.','/convenios':'Consulte valores, habilitações e vínculos, preservando cada fonte.','/credenciamento':'Acompanhe a situação dos convênios e as próximas ações por unidade.','/procedimentos':'Encontre códigos, descrições e referências para negociação.','/equipe':'Explore as equipes, setores e versões da estrutura organizacional.','/base':'Explore todas as abas e consulte os dados na sua posição original.','/qualidade':'Consulte as diferenças e lacunas identificadas durante a extração.'};
function Dashboard({data,unit,setUnit,go,onDetail}:{data:Library;unit:string;setUnit:(v:string)=>void;go:(p:string)=>void;onDetail:(d:Detail)=>void}) {
 const professionals=data.professionals.filter(p=>!unit||p.units.includes(unit));const gaps=data.gaps.filter(g=>!unit||g.unit===unit);const progress=gaps.filter(g=>g.status==='Em andamento').length;const approved=gaps.filter(g=>g.status==='Credenciado').length;
 const stats=[{label:'Profissionais na base',value:professionals.length,sub:'Identificados por conselho e registro',Icon:Stethoscope,path:'/corpo-clinico',color:'green'},{label:'Convênios no mapeamento',value:new Set(gaps.map(g=>g.payer)).size,sub:'Quadro de credenciamento por unidade',Icon:ShieldCheck,path:'/credenciamento',color:'blue'},{label:'Credenciamentos em andamento',value:progress,sub:'Posições por convênio e unidade',Icon:FileCheck2,path:'/credenciamento',color:'amber'},{label:'Unidades assistenciais',value:unit?1:data.units.length,sub:'Com corpo clínico na planilha',Icon:Building2,path:'/corpo-clinico',color:'purple'}];
 return <><section className="hero reveal"><div><Badge><span className="bright-dot"/> INFORMAÇÃO QUE APROXIMA</Badge><h2>Conectar informações.<br/><span>Ampliar possibilidades.</span></h2><p>Uma base organizada para apoiar quem faz<br className="desktop-break"/> o cuidado acontecer, todos os dias.</p><button onClick={()=>go('/credenciamento')} className="hero-button">Explorar credenciamentos <ArrowUpRight size={17}/></button></div><div className="hero-art" aria-hidden="true"><div className="orbit o1"/><div className="orbit o2"/><div className="orbit o3"/><div className="orbit o4"/><span className="art-dot d1"/><span className="art-dot d2"/><div className="hero-art-label"><span>ONCOLOGY</span><small>Pessoas. Conexões. Cuidado.</small></div></div><span className="hero-corner">UM ECOSSISTEMA DE CUIDADO</span></section>
 <div className="stats-grid">{stats.map(({label,value,sub,Icon,path,color})=><button onClick={()=>go(path)} className="stat-card reveal" key={label}><div className="stat-top"><span className={`stat-icon ${color}`}><Icon size={21}/></span><ArrowUpRight size={16}/></div><span className="stat-value">{value.toLocaleString('pt-BR')}</span><strong>{label}</strong><small>{sub}</small></button>)}</div>
 <section className="units-section reveal"><div className="section-heading"><div><h2>As unidades da nossa rede</h2><p>Selecione uma unidade para explorar suas informações.</p></div><button className="text-button" onClick={()=>{setUnit('');go('/corpo-clinico');}}>Ver corpo clínico <ArrowRight size={15}/></button></div><div className="units-grid">{data.units.map(u=><button className={`unit-card ${unit===u.id?'selected':''}`} key={u.id} onClick={()=>setUnit(unit===u.id?'':u.id)} aria-pressed={unit===u.id}><div className="unit-logo">{u.logo?<img src={u.logo} alt={u.name}/>:<span className="promater-wordmark"><HeartPulse size={24}/>Promater</span>}</div><div className="unit-card-bottom"><div><strong>{u.short}</strong><small>{data.professionals.filter(p=>p.units.includes(u.id)).length} profissionais</small></div><span style={{color:u.color}}><ArrowUpRight size={17}/></span></div></button>)}</div></section>
 <div className="dashboard-bottom"><section className="panel accreditation-panel reveal"><div className="panel-heading"><div><h2>Panorama de credenciamento</h2><p>Distribuição por unidade na matriz comercial</p></div><span className="small-icon"><ShieldCheck size={18}/></span></div><div className="chart-legend"><span><i className="legend-green"/>Credenciado</span><span><i className="legend-amber"/>Em andamento</span><span><i className="legend-gray"/>Outras situações</span></div><div className="bars">{data.units.filter(u=>u.id!=='PROMATER'&&(!unit||u.id===unit)).map(u=>{const gs=data.gaps.filter(g=>g.unit===u.id);const yes=gs.filter(g=>g.status==='Credenciado').length;const pending=gs.filter(g=>g.status==='Em andamento').length;return <button className="bar-row" key={u.id} onClick={()=>{setUnit(u.id);go('/credenciamento');}} aria-label={`${u.short}: ${yes} credenciados, ${pending} em andamento, ${gs.length-yes-pending} em outras situações`}><span>{u.short}</span><div className="stacked-bar"><i style={{width:`${yes/gs.length*100}%`}} className="legend-green"/><i style={{width:`${pending/gs.length*100}%`}} className="legend-amber"/><i style={{width:`${(gs.length-yes-pending)/gs.length*100}%`}} className="legend-gray"/></div><strong>{gs.length}</strong></button>;})}{unit==='PROMATER'&&<p className="muted">A matriz não inclui a Promater.</p>}</div><div className="panel-foot"><span><Check size={15}/><strong>{approved}</strong> posições credenciadas nesta visão</span><button className="text-button" onClick={()=>go('/credenciamento')}>Abrir matriz <ArrowRight size={14}/></button></div></section>
 <section className="panel attention-panel reveal"><div className="panel-heading"><div><h2>O que merece atenção</h2><p>Próximos passos registrados na base</p></div><span className="attention-dot"/></div>{gaps.filter(g=>g.status==='Em andamento').slice(0,3).map(g=><button className="attention-row" key={g.id} onClick={()=>onDetail({title:g.payer,values:{Unidade:unitName(g.unit),Situação:g.status,'Observação da fonte':g.detail},sources:[g.source]})}><span className="attention-icon"><FileText size={17}/></span><div><strong>{title(g.payer)}</strong><span>{unitName(g.unit)} · {g.detail.replace('⚠️','')}</span></div><ChevronRight size={15}/></button>)}{!progress&&<p className="muted attention-empty">Não há posições em andamento nesta visão.</p>}<button className="attention-link" onClick={()=>go('/qualidade')}><AlertCircle size={15}/>{data.issues.length} pontos para conferir na base<ArrowUpRight size={15}/></button></section></div>
 <section className="library-strip reveal"><div className="library-strip-icon"><Database size={22}/></div><div><h3>Da planilha à informação, sem perder a origem.</h3><p>{data.meta.nonemptyCells.toLocaleString('pt-BR')} células com conteúdo · Todas as 19 abas disponíveis para consulta.</p></div><button className="button secondary" onClick={()=>go('/base')}>Explorar biblioteca <ArrowRight size={15}/></button></section></>;
}
function Records({path,data,unit,query,onDetail}:{path:string;data:Library;unit:string;query:string;onDetail:(d:Detail)=>void}) {
 const [tab,setTab]=useState('primary');const [filter,setFilter]=useState('');const [day,setDay]=useState('');
 const matches=(s:string)=>norm(s).includes(norm(query));const inUnit=(u:string)=>!unit||u===unit;
 let columns:string[]=[];let rows:DisplayRow[]=[];let tabs:{id:string;label:string}[]=[];let filterOptions:{value:string;label:string}[]=[];let filterLabel='Todas as especialidades';let note='';
 if(path==='/corpo-clinico') {
  tabs=[{id:'primary',label:'Profissionais'},{id:'vinculos',label:'Vínculos e contratos'}];filterOptions=options(data.memberships.filter(m=>inUnit(m.unit)).map(m=>m.specialty));
  if(tab==='primary') { columns=['Profissional','Conselho / registro','Especialidades','Unidades'];rows=data.professionals.filter(p=>(!unit||p.units.includes(unit))&&(!filter||data.memberships.some(m=>m.professionalId===p.id&&inUnit(m.unit)&&m.specialty===filter))&&matches([p.name,...p.aliases,p.registration,...p.specialties].join(' '))).map(p=>({id:p.id,cells:[title(p.name),`${p.council} ${p.registration}`,[...new Set(p.specialties.map(title))].join(' · '),p.units.map(unitName).join(' · ')],details:{Nome:p.name,Registro:`${p.council} ${p.registration}`,'Grafias na fonte':p.aliases.join(' / '),'Especialidades na fonte':p.specialties.join(' / '),'Unidades e cadastros':p.units.map(unitName).join(' / '),'Vínculos / contratos':data.memberships.filter(m=>m.professionalId===p.id).map(m=>`${unitName(m.unit)} · ${m.section} · ${m.contract||'contrato não informado'} · RQE ${m.rqe||'não informado'}`).join('\n')},sources:p.sources})); }
  else {columns=['Profissional','Unidade / cadastro','Especialidade','Contrato'];rows=data.memberships.filter(m=>inUnit(m.unit)&&(!filter||m.specialty===filter)&&matches(`${m.name} ${m.registration} ${m.contract}`)).map(m=>({id:m.id,cells:[title(m.name),unitName(m.unit),title(m.specialty),m.contract||'Não informado'],details:{Nome:m.name,Registro:m.registration,RQE:m.rqe,Unidade:unitName(m.unit),Seção:m.section,Contrato:m.contract,'Data de entrada':date(m.startDate),'Data de nascimento':date(m.birthDate),'Nascimento original':m.birthDateRaw,CPF:m.cpf,'Dias de atendimento':m.days,Turno:m.shift,Observações:m.notes},source:m.source})); }
  note='Profissionais agrupados por conselho e registro. Vínculos, grafias e contratos permanecem associados às suas fontes.';
 } else if(path==='/atendimentos') {
  columns=['Profissional','Unidade','Dias de atendimento','Turno'];filterOptions=options(data.memberships.filter(m=>inUnit(m.unit)&&!['GROUP','GENERAL'].includes(m.unit)).map(m=>m.specialty));
  rows=data.memberships.filter(m=>!['GROUP','GENERAL'].includes(m.unit)&&inUnit(m.unit)&&(!filter||m.specialty===filter)&&(!day||norm(m.days).includes(day))&&matches(`${m.name} ${m.specialty} ${m.days} ${m.shift}`)).map(m=>({id:m.id,cells:[title(m.name),unitName(m.unit),m.days||'Não informado',m.shift||'Não informado'],details:{Profissional:m.name,Especialidade:m.specialty,Unidade:unitName(m.unit),Dias:m.days,Turno:m.shift,Observações:m.notes},source:m.source}));
  note='Disponibilidade transcrita da planilha, sem marcação de consultas. Horários ambíguos e atendimento quinzenal mantêm o texto original.';
 } else if(path==='/convenios') {
  tabs=[{id:'primary',label:'Valores por especialidade'},{id:'services',label:'Habilitação de serviços'},{id:'links',label:'Vínculos COMN'},{id:'lists',label:'Listas gerais'},{id:'notes',label:'Observações do mapeamento'}];
  if(tab==='primary') {columns=['Convênio','Especialidade','Unidade','Valor informado'];filterOptions=options(data.tariffs.filter(t=>inUnit(t.unit)).map(t=>t.specialty));rows=data.tariffs.filter(t=>inUnit(t.unit)&&(!filter||t.specialty===filter)&&matches(`${t.payer} ${t.specialty} ${t.context}`)).map(t=>({id:t.id,cells:[title(t.payer),title(t.specialty),unitName(t.unit),money(t.amount,t.amountRaw)],details:{Convênio:t.payer,Especialidade:t.specialty,Unidade:unitName(t.unit),Valor:money(t.amount,t.amountRaw),'Valor original':t.amountRaw,Contexto:t.context},source:t.source}));note='Valores do arquivo, sem indicação de vigência. Células vazias não significam valor zero. Compare as fontes nos detalhes.';}
  else if(tab==='services') {columns=['Convênio','Unidade','Serviços indicados','Marcação original'];filterLabel='Todas as marcações';filterOptions=options(data.services.map(s=>s.raw));rows=data.services.filter(s=>inUnit(s.unit)&&(!filter||s.raw===filter)&&matches(s.payer)).map((s,i)=>({id:String(i),cells:[title(s.payer),unitName(s.unit),[s.consultations?'Consultas':'',s.infusions?'Quimioterapia':'',s.procedures?'Serviços':''].filter(Boolean).join(' · ')||'Sem indicação afirmativa',s.raw||'Não informado'],source:s.source}));note='Símbolos transcritos da seção “Serviços, consultas e infusões”. Uma célula vazia ou “—” não confirma habilitação.';}
  else if(tab==='links') {columns=['Nome na exportação','Convênio / modalidade','Tipo','Observação'];filterLabel='Todos os tipos';filterOptions=options(data.links.map(l=>l.kind));rows=data.links.filter(l=>(!unit||unit==='COMN')&&(!filter||l.kind===filter)&&matches(`${l.name} ${l.payer}`)).map(l=>({id:l.id,cells:[title(l.name)||'Nome ausente',title(l.payer),l.kind,l.duplicate?'Par repetido':l.professionalId?'Associado ao cadastro':'Sem correspondência exata'],source:l.source}));note=`A exportação tem ${data.links.length} linhas e ${data.meta.duplicateLinks} repetições. Inclui formas de pagamento, serviços e nomes sem correspondência no corpo clínico.`;}
  else if(tab==='lists'){columns=['Convênio / modalidade','Lista de origem'];filterLabel='Todas as listas';filterOptions=options(data.payerLists.map(p=>p.kind));rows=data.payerLists.filter(p=>!filter||p.kind===filter).filter(p=>matches(p.payer)).filter(()=>!unit).map((p,i)=>({id:String(i),cells:[title(p.payer),p.kind],source:p.source}));note=unit?'Estas listas não têm uma unidade única. Limpe o filtro de unidade para consultá-las.':'Listas gerais independentes; não vinculam automaticamente convênios a profissionais ou unidades.';}
  else {columns=['Observação','Unidade','Especialidade'];rows=data.mappingNotes.filter(n=>inUnit(n.unit)&&matches(n.text)).map((n,i)=>({id:String(i),cells:[n.text,unitName(n.unit),title(n.specialty)],source:n.source}));note='Anotações de contexto preservadas separadamente dos nomes de convênios.';}
 } else if(path==='/credenciamento') {
  tabs=[{id:'primary',label:'Matriz de credenciamento'},{id:'mossoro',label:'Acompanhamento de Mossoró'}];
  if(tab==='primary'){columns=['Convênio','Unidade','Situação','Observação da fonte'];filterLabel='Todas as situações';filterOptions=options(data.gaps.map(g=>g.status));rows=data.gaps.filter(g=>inUnit(g.unit)&&(!filter||g.status===filter)&&matches(`${g.payer} ${g.detail}`)).map(g=>({id:g.id,cells:[title(g.payer),unitName(g.unit),g.status,g.detail],status:g.status,source:g.source}));note='Situações agrupadas para facilitar a leitura. A observação original define o contexto: “não solicitar”, “suspenso” e “aguardando” não são equivalentes.';}
  else{columns=['Convênio','Situação original','Acompanhamento'];rows=data.mossoro.filter(m=>(!unit||unit==='MOSSORO')&&matches(`${m.payer} ${m.status} ${m.notes}`)).map((m,i)=>({id:String(i),cells:[title(m.payer),m.status,m.notes],source:m.source}));note='Este quadro contém 20 registros, embora o título da planilha informe “TOTAL: 17”. A matriz e este acompanhamento são apresentados separadamente.';}
 } else if(path==='/procedimentos') {
  tabs=[{id:'primary',label:'Catálogo de procedimentos'},{id:'negotiations',label:'Base de negociação'},{id:'notes',label:'Condições e observações'}];filterLabel='Todas as categorias';
  if(tab==='primary') {columns=['Procedimento','Código','Categoria','Observações'];filterOptions=options(data.procedures.map(p=>p.category));rows=data.procedures.filter(p=>(!filter||p.category===filter)&&matches(`${p.description} ${p.code} ${p.category} ${p.notes}`)).map(p=>({id:p.id,cells:[p.description,p.code||'Sem código',title(p.category),p.notes||'—'],details:{Procedimento:p.description,Código:p.code,Categoria:p.category,Observações:p.notes,'Convênios habilitados':p.enabledPayers||'Não preenchidos na fonte','Não habilitados':p.disabledPayers||'Não preenchidos na fonte'},source:p.source}));note='Inclui descrições sem código e códigos reutilizados em diferentes procedimentos. Não representa validação externa de TUSS ou cobertura.';}
  else if(tab==='negotiations'){columns=['Descrição','Código','Valor de referência','Seção'];filterOptions=options(data.negotiations.map(n=>n.category));rows=data.negotiations.filter(n=>(!filter||n.category===filter)&&matches(`${n.description} ${n.code} ${n.section}`)).map(n=>({id:n.id,cells:[n.description,n.code,money(n.amount,n.amountRaw),title(n.section)],details:{Descrição:n.description,Código:n.code,Valor:money(n.amount,n.amountRaw),Seção:n.section,Base:n.basis,Observações:n.notes,'Uso':'Referência de negociação da planilha; não indica preço contratado.'},source:n.source}));note='Referências de negociação, com contextos e valores alternativos preservados. Consulte as condições antes de comparar itens.';}
  else{columns=['Condição / observação'];rows=data.negotiationNotes.filter(n=>matches(n.text)).map((n,i)=>({id:String(i),cells:[n.text],source:n.source}));note='Textos e condições extraídos da aba de negociações, incluindo exclusões, taxas e bases de cobrança.';}
  if(unit)note+=' Este catálogo é geral: a fonte não informa vínculo por unidade.';
 } else if(path==='/equipe') {
  filterLabel='Todos os setores';filterOptions=options(data.employees.filter(e=>inUnit(e.unit)).map(e=>e.department));tabs=[{id:'primary',label:'Todas as versões'},...data.sheets.slice(15).map(s=>({id:s.id,label:s.name.trim()}))];columns=['Profissional','Setor','Cargo','Unidade'];rows=data.employees.filter(e=>inUnit(e.unit)&&(tab==='primary'||e.source.sheetId===tab)&&(!filter||e.department===filter)&&matches(`${e.name} ${e.department} ${e.role}`)).map(e=>({id:e.id,cells:[title(e.name),title(e.department),e.role,unitName(e.unit)],details:{Nome:e.name,Setor:e.department,Cargo:e.role,Unidade:unitName(e.unit),Grupo:e.section,'Data de nascimento':date(e.birthDate)},source:e.source}));note='As quatro versões permanecem separadas. A contagem representa registros, não pessoas únicas; unidades ausentes não foram inferidas.';
 }
 return <div className="reveal">{tabs.length>0&&<div className="tabs" role="tablist" aria-label="Visões da consulta">{tabs.map(t=><button key={t.id} role="tab" aria-selected={tab===t.id} onClick={()=>{setTab(t.id);setFilter('');}} className={tab===t.id?'active':''}>{t.label}</button>)}</div>}<div className="view-controls"><div><SlidersHorizontal size={15}/>{filterOptions.length>0&&<Filter label={filterLabel} value={filter} options={filterOptions} onChange={setFilter}/>} {path==='/atendimentos'&&<Filter label="Todos os dias" value={day} options={['Segunda','Terça','Quarta','Quinta','Sexta'].map(d=>({value:norm(d),label:d+'-feira'}))} onChange={setDay}/>}</div>{(filter||day)&&<button className="text-button" onClick={()=>{setFilter('');setDay('');}}>Limpar filtros da tabela</button>}</div><div className="info-note"><CircleHelp size={16}/><p>{note}</p></div><DataTable columns={columns} rows={rows} onDetail={onDetail}/></div>;
}
function SearchResults({data,query,unit,onDetail}:{data:Library;query:string;unit:string;onDetail:(d:Detail)=>void}) {
 const matches=(s:string)=>norm(s).includes(norm(query));
 const rows:DisplayRow[]=[...data.professionals.filter(p=>(!unit||p.units.includes(unit))&&matches([p.name,...p.aliases,p.registration,...p.specialties].join(' '))).map(p=>({id:p.id,cells:[title(p.name),'Profissional',p.specialties.join(' · ')],sources:p.sources})),...data.tariffs.filter(t=>(!unit||t.unit===unit)&&matches(`${t.payer} ${t.specialty}`)).map(t=>({id:t.id,cells:[title(t.payer),'Convênio / valor',`${unitName(t.unit)} · ${t.specialty} · ${money(t.amount,t.amountRaw)}`],source:t.source})),...data.procedures.filter(p=>matches(`${p.description} ${p.code}`)).map(p=>({id:p.id,cells:[p.description,'Procedimento · catálogo geral',p.code],source:p.source}))];
 return <div className="reveal"><div className="section-heading"><h2>Resultados para “{query}”</h2></div><DataTable columns={['Registro','Tipo','Informações']} rows={rows} onDetail={onDetail}/></div>;
}
function Quality({data,onDetail}:{data:Library;onDetail:(d:Detail)=>void}) {
 const [filter,setFilter]=useState('');const [query,setQuery]=useState('');
 return <div className="reveal"><div className="quality-summary"><div><span className="stat-icon amber"><AlertCircle size={24}/></span><h2>Preservar a informação.<br/>Dar visibilidade às diferenças.</h2><p>As versões da planilha são exibidas lado a lado. Nenhum valor conflitante é escolhido automaticamente.</p></div><strong>{data.issues.length}<small>pontos de conferência</small></strong></div><div className="global-filters"><label className="search-control"><Search size={17}/><input aria-label="Buscar pontos de conferência" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar pontos de conferência…"/></label><Filter label="Todos os tipos" value={filter} options={options(data.issues.map(i=>i.kind))} onChange={setFilter}/></div><DataTable columns={['Ponto de conferência','Tipo','Fontes']} rows={data.issues.filter(i=>(!filter||i.kind===filter)&&norm(i.message+' '+i.kind).includes(norm(query))).map(i=>({id:i.id,cells:[i.message,i.kind,String(i.sources.length)],sources:i.sources}))} onDetail={onDetail}/></div>;
}
function WorkbookView({data}:{data:Library}) {
 const [params,setParams]=useSearchParams();const sheetId=params.get('aba')||data.sheets[0].id;const rowNumber=Number(params.get('linha'));
 const [workbook,setWorkbook]=useState<Workbook|null>(null);const [error,setError]=useState('');const [query,setQuery]=useState('');const [page,setPage]=useState(0);const [reveal,setReveal]=useState(false);
 useEffect(()=>{const controller=new AbortController();apiFetch('/api/workbook',{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error('Não foi possível carregar as abas.');return r.json();}).then(setWorkbook).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[]);
 const sheet=workbook?.sheets.find(s=>s.id===sheetId)||workbook?.sheets[0];
 const filtered=useMemo(()=>sheet?.rows.filter(r=>Object.values(r.cells).some(v=>v.trim())&&norm(Object.values(r.cells).join(' ')).includes(norm(query)))||[],[sheet,query]);
 useEffect(()=>{setQuery('');setReveal(false);},[sheetId]);
 useEffect(()=>{const index=filtered.findIndex(r=>r.row===rowNumber);setPage(index>=0?Math.floor(index/25):0);},[filtered,rowNumber]);
 const columns=useMemo(()=>[...new Set(filtered.flatMap(r=>Object.keys(r.cells)))].sort((a,b)=>a.length-b.length||a.localeCompare(b)),[filtered]);
 const pages=Math.max(1,Math.ceil(filtered.length/25));const current=Math.min(page,pages-1);
 const personal=(c:string,r:number)=>{const i=data.sheets.findIndex(s=>s.id===sheetId);return (i<7&&i!==1&&['E','F'].includes(c)&&r>2)||(i===15||i===16)&&['D','I','N'].includes(c)&&![2,31].includes(r)||(i===17&&c==='N'&&r===25);};
 return <div className="reveal"><div className="workbook-top"><label className="workbook-selector">Aba da planilha<Filter label="Selecione a aba" value={sheetId} onChange={v=>setParams({aba:v||data.sheets[0].id})} options={data.sheets.map(s=>({value:s.id,label:`${s.name.trim()} (${s.rowCount})`}))}/></label><button className="button secondary" onClick={()=>setReveal(!reveal)}>{reveal?'Ocultar':'Mostrar'} dados pessoais</button><button className="button secondary" disabled={!workbook} onClick={()=>download('oncology-planilha-completa.json',JSON.stringify(workbook,null,2),'application/json')}><ArrowDownToLine size={15}/>JSON completo</button></div><div className="info-note"><FileSpreadsheet size={17}/><p>Conteúdo original por coordenada. Datas podem aparecer como números seriais do Excel; os módulos de consulta fazem a conversão. Os textos são dados da planilha, inclusive suas anotações operacionais.</p></div><label className="search-control workbook-search"><Search size={17}/><input aria-label="Buscar na aba" placeholder="Buscar conteúdo nesta aba…" value={query} onChange={e=>{setQuery(e.target.value);setParams({aba:sheetId});}}/></label>{error?<p role="alert">{error}</p>:!sheet?<p>Carregando todas as abas…</p>:<section className="panel data-panel"><div className="table-toolbar"><span><strong>{sheet.name}</strong> · {filtered.length} linhas</span><Badge>Original preservado</Badge></div><div className="table-scroll workbook-scroll"><table className="workbook-table"><thead><tr><th>Linha</th>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{filtered.slice(current*25,current*25+25).map(r=><tr key={r.row} className={r.row===rowNumber?'highlight-row':''}><th>{r.row}</th>{columns.map(c=><td key={c} title={`${c}${r.row}`}>{personal(c,r.row)&&!reveal&&r.cells[c]?'•••':r.cells[c]||''}{r.meta[c]?.formula&&<small>Fórmula: {r.meta[c].formula}</small>}</td>)}</tr>)}</tbody></table>{!filtered.length&&<div className="empty-state"><h3>Nenhuma linha encontrada</h3></div>}</div><div className="pagination"><span>{filtered.length?`${current*25+1}–${Math.min(current*25+25,filtered.length)} de ${filtered.length}`:'0 linhas'}</span><div><button className="icon-button" aria-label="Página anterior" disabled={!current} onClick={()=>setPage(current-1)}><ChevronLeft size={16}/></button><span>{current+1} / {pages}</span><button className="icon-button" aria-label="Próxima página" disabled={current===pages-1} onClick={()=>setPage(current+1)}><ChevronRight size={16}/></button></div></div></section>}</div>;
}
