import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { X, Plus, Trash2, Save, AlertCircle, Building2 } from 'lucide-react';
import { logoOptions, states, labelCase, type GuideData, type GuideProfessional, type GuideUnit, type GuideExam, type Placement } from './guide-types';
export type SaveRecord = (kind: 'professionals'|'units'|'exams', id: string|null, record: unknown, revision: number) => Promise<void>;
const splitLines=(s:string)=>s.split(/[\n;]/).map(v=>v.trim()).filter(Boolean);
const newPlacement=(unitId=''):Placement=>({unitId,specialties:[],payers:[],schedules:[],notes:'',active:true});
function Dialog({title,description,children,close,dirty}:{title:string;description:string;children:ReactNode;close:()=>void;dirty:boolean}) {
 const ref=useRef<HTMLDialogElement>(null);
 const cancel=()=>{if(!dirty||window.confirm('Descartar as alterações que ainda não foram salvas?'))close();};
 useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close();},[]);
 useEffect(()=>{const before=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[dirty]);
 return <dialog className="edit-dialog" ref={ref} aria-labelledby="editor-title" onCancel={e=>{e.preventDefault();cancel();}}><div className="editor-heading"><div><span className="eyebrow">ADMINISTRAÇÃO DA REDE</span><h2 id="editor-title">{title}</h2><p>{description}</p></div><button type="button" className="icon-button" aria-label="Fechar formulário" onClick={cancel}><X size={21}/></button></div>{children}</dialog>;
}
function Field({label,children,wide=false,hint}:{label:string;children:ReactNode;wide?:boolean;hint?:string}){return <label className={wide?'field wide':'field'}><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
function Footer({busy}:{busy:boolean}){return <footer className="editor-footer"><span>Alterações salvas no servidor.</span><button className="button primary" type="submit" disabled={busy}><Save size={16}/>{busy?'Salvando…':'Salvar cadastro'}</button></footer>;}
function ErrorMessage({message}:{message:string}){return message?<div className="form-error" role="alert"><AlertCircle size={18}/>{message}</div>:null;}
export function ProfessionalForm({data,person,unitId,save,close}:{data:GuideData;person?:GuideProfessional;unitId?:string;save:SaveRecord;close:()=>void}){
 const initial=person||{name:'',council:'CRM',registration:'',uf:'',rqe:'',notes:'',placements:[newPlacement(unitId)]};
 const [draft,setDraft]=useState(()=>structuredClone(initial));const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [revision]=useState(data.revision);
 const dirty=JSON.stringify(draft)!==JSON.stringify(initial);
 const patch=(name:string,value:string)=>setDraft(p=>({...p,[name]:value}));
 const placement=(index:number,value:Partial<Placement>)=>setDraft(p=>({...p,placements:p.placements.map((a,i)=>i===index?{...a,...value}:a)}));
 const submit=async(e:FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await save('professionals',person?.id||null,draft,revision);close();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Dialog title={person?'Editar profissional':'Cadastrar profissional'} description="Um cadastro pessoal. Informações de atendimento independentes em cada unidade." close={close} dirty={dirty}><form onSubmit={submit}><fieldset disabled={busy} className="editor-fields"><div className="form-section-title"><span>01</span><div><h3>Identificação do profissional</h3><p>Use o conselho e o registro para evitar cadastros duplicados.</p></div></div><div className="form-grid"><Field label="Nome completo" wide><input required maxLength={200} value={draft.name} onChange={e=>patch('name',e.target.value)} autoComplete="off"/></Field><Field label="Conselho"><input required maxLength={12} value={draft.council} onChange={e=>patch('council',e.target.value.toUpperCase())} placeholder="CRM, CRN, CRP…"/></Field><Field label="Número do registro"><input required inputMode="numeric" pattern="[0-9]+" maxLength={15} value={draft.registration} onChange={e=>patch('registration',e.target.value)}/></Field><Field label="UF do registro"><select value={draft.uf} onChange={e=>patch('uf',e.target.value)}><option value="">Não informada</option>{states.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="RQE"><input value={draft.rqe} maxLength={500} onChange={e=>patch('rqe',e.target.value)} placeholder="Quando informado"/></Field><Field label="Observações do profissional" wide><textarea value={draft.notes} maxLength={2000} onChange={e=>patch('notes',e.target.value)} rows={2}/></Field></div>
 <div className="form-section-title"><span>02</span><div><h3>Vínculos e atendimento</h3><p>Cadastre convênios e horários somente na unidade correspondente.</p></div></div>
 {draft.placements.map((a,i)=><section className="placement-editor" key={i}><div className="placement-top"><h4><Building2 size={17}/>Vínculo {i+1}</h4><label className="checkbox-label"><input type="checkbox" checked={a.active} onChange={e=>placement(i,{active:e.target.checked})}/>Vínculo ativo</label></div><div className="form-grid"><Field label={`Unidade do vínculo ${i+1}`} wide><select required value={a.unitId} onChange={e=>placement(i,{unitId:e.target.value})}><option value="">Selecione a unidade</option>{data.units.map(u=><option key={u.id} value={u.id} disabled={draft.placements.some((p,j)=>j!==i&&p.unitId===u.id)}>{u.name}</option>)}</select></Field><Field label={`Especialidades do vínculo ${i+1}`} wide hint="Uma especialidade por linha ou separada por ponto e vírgula."><ListInput values={a.specialties} required onChange={v=>placement(i,{specialties:v})}/></Field><Field label={`Convênios do vínculo ${i+1}`} wide hint="Um convênio por linha. Em branco significa que não foi informado."><ListInput values={a.payers} onChange={v=>placement(i,{payers:v})}/></Field></div>
 <div className="schedule-heading"><strong>Dias e turnos</strong><button type="button" className="text-button" onClick={()=>placement(i,{schedules:[...a.schedules,{days:'',shift:'',notes:''}]})}><Plus size={14}/>Adicionar horário</button></div>{!a.schedules.length&&<p className="form-hint">Nenhum horário informado para esta unidade.</p>}{a.schedules.map((s,j)=><div className="schedule-editor" key={j}><Field label={`Dias do horário ${j+1}, vínculo ${i+1}`}><input maxLength={200} placeholder="Ex.: segunda e quarta" value={s.days} onChange={e=>placement(i,{schedules:a.schedules.map((v,k)=>k===j?{...v,days:e.target.value}:v)})}/></Field><Field label={`Turno do horário ${j+1}, vínculo ${i+1}`}><input maxLength={300} placeholder="Ex.: manhã, 8h às 12h" value={s.shift} onChange={e=>placement(i,{schedules:a.schedules.map((v,k)=>k===j?{...v,shift:e.target.value}:v)})}/></Field><Field label={`Observação do horário ${j+1}, vínculo ${i+1}`}><input maxLength={1000} placeholder="Quinzenal, sala, observação…" value={s.notes} onChange={e=>placement(i,{schedules:a.schedules.map((v,k)=>k===j?{...v,notes:e.target.value}:v)})}/></Field><button className="icon-button danger" aria-label={`Remover horário ${j+1} do vínculo ${i+1}`} type="button" onClick={()=>placement(i,{schedules:a.schedules.filter((_,k)=>j!==k)})}><Trash2 size={16}/></button></div>)}<Field label={`Observações do vínculo ${i+1}`}><textarea rows={2} maxLength={2000} value={a.notes} onChange={e=>placement(i,{notes:e.target.value})}/></Field>{!person&&draft.placements.length>1&&<button type="button" className="text-button danger" onClick={()=>setDraft(p=>({...p,placements:p.placements.filter((_,j)=>i!==j)}))}>Remover vínculo</button>}</section>)}
 <button type="button" className="button secondary" disabled={draft.placements.length>=data.units.length} onClick={()=>setDraft(p=>({...p,placements:[...p.placements,newPlacement()]}))}><Plus size={16}/>Adicionar outra unidade</button></fieldset><div className="editor-message"><ErrorMessage message={error}/></div><Footer busy={busy}/></form></Dialog>;
}
// Keep the text being typed intact while emitting a normalized list to the form model.
function ListInput({values,onChange,required=false}:{values:string[];onChange:(v:string[])=>void;required?:boolean}){const [text,setText]=useState(values.join('\n'));return <textarea rows={3} value={text} maxLength={15000} required={required} onChange={e=>{setText(e.target.value);onChange(splitLines(e.target.value));}}/>;}
export function UnitForm({data,unit,save,close}:{data:GuideData;unit:GuideUnit;save:SaveRecord;close:()=>void}){
 const [draft,setDraft]=useState({...unit});const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [revision]=useState(data.revision);
 const patch=(field:string,value:string|null)=>setDraft(p=>({...p,[field]:value}));
 const submit=async(e:FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);try{await save('units',unit.id,draft,revision);close();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Dialog title="Dados da unidade" description="Identificação da clínica e da empresa responsável. Campos desconhecidos podem ficar em branco." close={close} dirty={JSON.stringify(draft)!==JSON.stringify(unit)}><form onSubmit={submit}><fieldset disabled={busy} className="editor-fields form-grid"><Field label="Nome da unidade" wide><input required value={draft.name} onChange={e=>patch('name',e.target.value)} maxLength={200}/></Field><Field label="Nome curto"><input required value={draft.short} onChange={e=>patch('short',e.target.value)} maxLength={70}/></Field><Field label="CNPJ" hint="Informe apenas se confirmado para esta unidade."><input value={draft.cnpj} onChange={e=>patch('cnpj',e.target.value)} maxLength={25} placeholder="Não informado"/></Field><Field label="Razão social" wide><input value={draft.legalName} onChange={e=>patch('legalName',e.target.value)} maxLength={300} required={!!draft.cnpj}/></Field><Field label="Logo oficial" wide><select value={draft.logo||''} onChange={e=>patch('logo',e.target.value||null)}><option value="">Sem logo disponível</option>{logoOptions.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></Field>{draft.logo&&<img className="form-logo-preview" src={draft.logo} alt="Prévia da logo"/>}</fieldset><div className="editor-message"><ErrorMessage message={error}/></div><Footer busy={busy}/></form></Dialog>;
}
export function ExamForm({data,unitId,exam,save,close}:{data:GuideData;unitId:string;exam?:GuideExam;save:SaveRecord;close:()=>void}){
 const initial:Omit<GuideExam,'id'|'updatedAt'>=exam?{unitId:exam.unitId,name:exam.name,code:exam.code,category:exam.category,description:exam.description,payers:exam.payers,professionalIds:exam.professionalIds,active:exam.active}:{name:'',unitId,code:'',category:'',description:'',payers:[],professionalIds:[],active:true};
 const [draft,setDraft]=useState<Omit<GuideExam,'id'|'updatedAt'>>(()=>structuredClone(initial));const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [revision]=useState(data.revision);const [catalogSearch,setCatalogSearch]=useState('');
 const patch=(name:string,value:string)=>setDraft(p=>({...p,[name]:value}));
 const people=data.professionals.filter(p=>p.placements.some(a=>a.unitId===unitId&&a.active));
 const submit=async(e:FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);try{await save('exams',exam?.id||null,draft,revision);close();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Dialog title={exam?'Editar exame':'Cadastrar exame na unidade'} description="Informe os serviços efetivamente oferecidos aqui. O catálogo é uma referência para preencher o cadastro." close={close} dirty={JSON.stringify(draft)!==JSON.stringify(initial)}><form onSubmit={submit}><fieldset disabled={busy} className="editor-fields"><div className="form-grid"><Field label="Usar um item do catálogo" wide><input placeholder="Buscar descrição ou código…" value={catalogSearch} onChange={e=>setCatalogSearch(e.target.value)}/></Field>{catalogSearch&&<div className="catalog-results wide">{data.catalog.filter(c=>(c.name+' '+c.code).toLocaleLowerCase().includes(catalogSearch.toLocaleLowerCase())).slice(0,15).map(c=><button type="button" key={c.id} onClick={()=>{setDraft(p=>({...p,name:c.name,code:c.code,category:c.category}));setCatalogSearch('');}}><strong>{c.name}</strong><small>{c.code||'Sem código'} · {c.category}</small></button>)}</div>}<Field label="Nome do exame" wide><input required maxLength={500} value={draft.name} onChange={e=>patch('name',e.target.value)}/></Field><Field label="Código"><input maxLength={30} value={draft.code} onChange={e=>patch('code',e.target.value)}/></Field><Field label="Categoria"><input maxLength={150} value={draft.category} onChange={e=>patch('category',e.target.value)}/></Field><Field label="Informações do exame" wide><textarea maxLength={3000} rows={3} value={draft.description} onChange={e=>patch('description',e.target.value)}/></Field><Field label="Convênios do exame" wide><ListInput values={draft.payers} onChange={payers=>setDraft(p=>({...p,payers}))}/></Field></div><h3 className="form-subtitle">Profissionais nesta unidade</h3><div className="doctor-checklist">{people.map(p=><label className="checkbox-label" key={p.id}><input type="checkbox" checked={draft.professionalIds.includes(p.id)} onChange={e=>setDraft(d=>({...d,professionalIds:e.target.checked?[...d.professionalIds,p.id]:d.professionalIds.filter(id=>id!==p.id)}))}/>{labelCase(p.name)}</label>)}{!people.length&&<p>Nenhum profissional com vínculo ativo nesta unidade.</p>}</div><label className="checkbox-label"><input type="checkbox" checked={draft.active} onChange={e=>setDraft(p=>({...p,active:e.target.checked}))}/>Exame ativo nesta unidade</label></fieldset><div className="editor-message"><ErrorMessage message={error}/></div><Footer busy={busy}/></form></Dialog>;
}
